use stable inmanta-core api
inmanta/inmanta-sphinx pull request #43
Opened 2021-04-13 09:07 UTC by sanderr

# Description

Use stable inmanta-core api (see #2854). After merging this I plan to take the following steps:
- release 1.4.0
- bump inmanta-sphinx dependency for inmanta-dev-dependencies
- bump inmanta-dev-dependencies for the product repos
I believe this should resolve all current docs build failures.

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Code is clear and sufficiently documented
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-04-13 09:33 UTC, arnaudsjs requested changes

2021-04-13 09:33 UTC, arnaudsjs commented on sphinxcontrib/inmanta/api.py
> +        except module.InvalidMetadata:
This raises an `InvalidModuleException` when the module doesn't exist.

2021-04-13 09:41 UTC, arnaudsjs approved these changes

2021-04-14 13:54 UTC, wouterdb approved these changes

2021-04-14 14:26 UTC, merged